Hw2
KristinaBeslic/android-vjestina-tmdb pull request #2
Opened 2022-11-20 23:03 UTC by KristinaBeslic

2022-11-23 15:09 UTC, ivan-varga requested changes

2022-11-23 15:09 UTC, ghost commented on app/src/main/java/agency/five/codebase/android/movieapp/ui/home/HomeScreen.kt
> +                0, 1, 2, 3 -> {
Use `.ordinal` properties of enums to resolve categoryId. 
Such as:
```kotlin
MovieCategory.POPULAR_STREAMING.ordinal
```

2022-11-23 15:09 UTC, ghost commented on app/src/main/java/agency/five/codebase/android/movieapp/ui/main/MainScreen.kt
> +                        navController.navigateUp()
You don't need this

2022-11-23 15:09 UTC, ivan-varga commented on app/src/main/java/agency/five/codebase/android/movieapp/ui/main/MainScreen.kt
> +                    showBottomBar = true
This solution doesn’t scale well. Imagine that you need to add more screens, than you’ll have to put the logic for showing bottomBar/backIcon into every screen:
```kotlin
composable(someRoute) {
  showBottomBar = true/false
  showBackIcon = false/true
}
```
You can use provided navBackStackEntry for calculating showBottomBar:
```kotlin
val showBottomBar = when (navBackStackEntry?.destination?.route) {
    MovieDetailsDestination.route -> false
    else -> true
}

val showBackIcon = !showBottomBar
```

2022-11-23 15:09 UTC, ivan-varga commented on app/src/main/java/agency/five/codebase/android/movieapp/ui/main/MainScreen.kt
> +fun RowScope.AddItem(
Should just be called `Item` or `BottomNavItem` or something similar.
Composable functions represent a UI component and not an action to be performed (AddItem -> Item).

2022-11-23 15:11 UTC, ivan-varga commented
@KristinaBeslic 
> On card click navigation doesn't work properly, top billed cast on movie details screen doesn't show properly

Please schedule consultations with a member of our team to review this in more detail

2022-11-27 21:38 UTC, KristinaBeslic commented
> @KristinaBeslic
> 
> > On card click navigation doesn't work properly, top billed cast on movie details screen doesn't show properly
> 
> Please schedule consultations with a member of our team to review this in more detail

Solved :)

2022-11-28 13:18 UTC, ghost approved these changes
🚀

2022-11-30 07:37 UTC, merged